### ISSUE TITLE
[US]: Entrainement migration site web 

### ISSUE THREAD

**Issue by Munozmu** [Anthonycbrl/Triathlon-TOAC-G1#49]
US requested by PSO

S'entrainer à envoyer le site et ses données sur un autre serveur (un autre serveur AWS d'entrainement ?) pour voir si tout se passe bien pour éviter de se louper le jour où on doit envoyer les datas sur le vrai serveur.

 @quentin-beaufort point particulier pour toi

**Comment by quentin-beaufort** [comment]
Pas possible d'ouvrir un autre aws, voir si qq un peut ouvrir un oracle
